from app.models.transcript import Expert, TranscriptSegment


EXPERTS = [
    Expert(
        name="Dr. Jean Martin",
        role="Head of Urology",
        market="France",
        transcript_id="expert_1_france",
    ),
    Expert(
        name="Anna Keller",
        role="Former Hospital Procurement Director",
        market="Germany",
        transcript_id="expert_2_germany",
    ),
    Expert(
        name="Dr. Emily Carter",
        role="Consultant Urologist",
        market="United Kingdom",
        transcript_id="expert_3_uk",
    ),
]


TRANSCRIPTS = {
    "expert_1_france": [
        TranscriptSegment(
            id="fr_001",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="00:00",
            text="Thanks for joining. To begin, how would you describe robotic surgery adoption in France today?",
        ),
        TranscriptSegment(
            id="fr_002",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="00:18",
            text="Adoption is growing, but it is still concentrated in larger academic hospitals and private centres with stronger capital budgets. Smaller regional hospitals are much slower.",
        ),
        TranscriptSegment(
            id="fr_003",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="01:12",
            text="What is holding adoption back?",
        ),
        TranscriptSegment(
            id="fr_004",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="01:20",
            text="The biggest issue is still capital budget approval. Hospitals may like the technology clinically, but purchasing committees need a strong economic case before approving a system.",
        ),
        TranscriptSegment(
            id="fr_005",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="02:14",
            text="So ROI is important?",
        ),
        TranscriptSegment(
            id="fr_006",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="02:18",
            text="Very important. The clinical argument may get surgeons interested, but the finance team wants to understand utilisation, procedure volume, maintenance cost and whether the system will actually pay for itself.",
        ),
        TranscriptSegment(
            id="fr_007",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="03:05",
            text="What about training?",
        ),
        TranscriptSegment(
            id="fr_008",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="03:10",
            text="Training matters, especially in the first year. If only one surgeon can use the system, the economics become difficult. Hospitals want several surgeons trained so utilisation is high enough.",
        ),
        TranscriptSegment(
            id="fr_009",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="04:02",
            text="Are clinical outcomes still the main driver?",
        ),
        TranscriptSegment(
            id="fr_010",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="04:08",
            text="Clinical outcomes are necessary, but they are not enough on their own. If two systems offer similar outcomes, the hospital will look hard at economics and utilisation.",
        ),
        TranscriptSegment(
            id="fr_011",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="05:00",
            text="What do you expect over the next three to five years?",
        ),
        TranscriptSegment(
            id="fr_012",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="05:07",
            text="I expect adoption to continue increasing, probably steadily rather than explosively. I would expect maybe 15 to 20 percent more procedures annually in some of the stronger centres, but smaller hospitals will remain slower.",
        ),
        TranscriptSegment(
            id="fr_013",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Interviewer",
            timestamp="06:02",
            text="How long does a purchase decision normally take?",
        ),
        TranscriptSegment(
            id="fr_014",
            expert="Dr. Jean Martin",
            role="Head of Urology",
            market="France",
            speaker="Dr. Martin",
            timestamp="06:08",
            text="Six to twelve months is realistic once the hospital becomes serious. It can be longer if the capital committee pushes the purchase into the next budget cycle.",
        ),
    ],

    "expert_2_germany": [
        TranscriptSegment(
            id="de_001",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="00:00",
            text="How would you describe robotic surgery adoption in Germany today?",
        ),
        TranscriptSegment(
            id="de_002",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="00:16",
            text="It is growing, but adoption is quite uneven. Large university hospitals are much more advanced, while many smaller hospitals are still waiting.",
        ),
        TranscriptSegment(
            id="de_003",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="01:05",
            text="What are the main barriers?",
        ),
        TranscriptSegment(
            id="de_004",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="01:10",
            text="Cost is the first barrier. These are large capital purchases, and hospital finances are under pressure. The second issue is proving that the system will be used enough.",
        ),
        TranscriptSegment(
            id="de_005",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="02:03",
            text="What does procurement focus on?",
        ),
        TranscriptSegment(
            id="de_006",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="02:08",
            text="We look at total cost of ownership, expected procedure volume, maintenance, service contracts and training requirements. A strong clinical case helps, but the economic case decides whether it gets approved.",
        ),
        TranscriptSegment(
            id="de_007",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="03:00",
            text="How important is surgeon training?",
        ),
        TranscriptSegment(
            id="de_008",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="03:05",
            text="Very important operationally. If the hospital buys a system but only one surgeon is comfortable using it, utilisation will be poor. That weakens the business case.",
        ),
        TranscriptSegment(
            id="de_009",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="04:04",
            text="Do you expect adoption to accelerate?",
        ),
        TranscriptSegment(
            id="de_010",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="04:09",
            text="Yes, but I would not expect a dramatic jump. I think growth will be gradual, especially because many hospitals have other competing capital priorities.",
        ),
        TranscriptSegment(
            id="de_011",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="05:02",
            text="Any rough expectation over the next three to five years?",
        ),
        TranscriptSegment(
            id="de_012",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="05:08",
            text="I would expect continued growth, but probably closer to high single digits or low double digits in procedure volumes rather than something like 20 percent across the whole market.",
        ),
        TranscriptSegment(
            id="de_013",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Interviewer",
            timestamp="06:00",
            text="How long can the purchase process take?",
        ),
        TranscriptSegment(
            id="de_014",
            expert="Anna Keller",
            role="Former Hospital Procurement Director",
            market="Germany",
            speaker="Anna Keller",
            timestamp="06:05",
            text="Nine to eighteen months is common. Procurement, clinical leadership, finance and management all need to align, so it can move slowly.",
        ),
    ],

    "expert_3_uk": [
        TranscriptSegment(
            id="uk_001",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="00:00",
            text="How would you describe adoption in the UK?",
        ),
        TranscriptSegment(
            id="uk_002",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="00:14",
            text="Adoption is increasing, and in some larger NHS trusts robotic surgery is becoming standard for selected procedures. But access still varies significantly by hospital.",
        ),
        TranscriptSegment(
            id="uk_003",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="01:00",
            text="What are the main barriers?",
        ),
        TranscriptSegment(
            id="uk_004",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="01:05",
            text="Funding is important, but I would say training capacity is just as important. You can buy a system, but if you cannot train enough surgeons and theatre staff, adoption stalls.",
        ),
        TranscriptSegment(
            id="uk_005",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="02:02",
            text="How important is ROI?",
        ),
        TranscriptSegment(
            id="uk_006",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="02:07",
            text="It matters, but the discussion is not always purely financial. Hospitals also consider patient outcomes, length of stay, surgeon recruitment and whether the technology improves their clinical position.",
        ),
        TranscriptSegment(
            id="uk_007",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="03:03",
            text="So would you say economics are less important in the UK?",
        ),
        TranscriptSegment(
            id="uk_008",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="03:10",
            text="I would say economics and clinical strategy are balanced. I would not say finance alone decides the purchase.",
        ),
        TranscriptSegment(
            id="uk_009",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="04:01",
            text="What is your outlook for the next three to five years?",
        ),
        TranscriptSegment(
            id="uk_010",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="04:06",
            text="I am quite positive. I think adoption could accelerate if training expands and systems become more cost competitive. I could see procedure growth above 15 percent annually in some areas.",
        ),
        TranscriptSegment(
            id="uk_011",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="05:00",
            text="What about purchase timelines?",
        ),
        TranscriptSegment(
            id="uk_012",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="05:04",
            text="Around six to nine months can happen if funding is already available. If the trust has to wait for a new capital cycle, it can take much longer.",
        ),
        TranscriptSegment(
            id="uk_013",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Interviewer",
            timestamp="06:00",
            text="Any final thought?",
        ),
        TranscriptSegment(
            id="uk_014",
            expert="Dr. Emily Carter",
            role="Consultant Urologist",
            market="United Kingdom",
            speaker="Dr. Carter",
            timestamp="06:04",
            text="The key point is that adoption is not just about buying the machine. Hospitals need enough trained people and enough procedure volume to make the programme sustainable.",
        ),
    ],
}


def get_all_segments() -> list[TranscriptSegment]:
    segments = []

    for transcript_segments in TRANSCRIPTS.values():
        segments.extend(transcript_segments)

    return segments


def get_experts() -> list[Expert]:
    return EXPERTS